# Generated by Django 3.1.2 on 2020-10-22 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('treningtype', models.CharField(choices=[('non', '--------'), ('ski', 'Ski'), ('lop', 'Løpe'), ('svm', 'Svømming'), ('sty', 'Styrke')], default='non', max_length=3, verbose_name='Treningstype')),
                ('distance', models.FloatField(blank=True, default=0, null=True, verbose_name='Distanse')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Dato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
