# Generated by Django 3.1.2 on 2020-10-15 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treningtype', models.IntegerField(choices=[(0, '--------'), (1, 'Ski'), (2, 'Løpe'), (3, 'Svømming'), (4, 'Styrke')], default=0, verbose_name='Treningstype')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distanse')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Dato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
