# Generated by Django 3.1.2 on 2020-10-15 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treningtype', models.IntegerField(choices=[(0, '--------'), (1, 'Ski'), (2, 'Løpe'), (3, 'Svømming'), (4, 'Styrke')], default=0, verbose_name='Treningstype')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distanse')),
                ('date', models.DateField(default=datetime.datetime(2020, 10, 15, 19, 45, 5, 852898), verbose_name='Dato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name': 'trening',
                'verbose_name_plural': 'treninger',
            },
        ),
    ]
