# Generated by Django 3.1.2 on 2020-10-15 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 15, 20, 24, 24, 892712), verbose_name='Dato'),
        ),
    ]
